version: '3.9'
services:
  frontend:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: always
