// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwedwkokcvwmzeutrygi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3ZWR3a29rY3Z3bXpldXRyeWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTUzMTUsImV4cCI6MjA2NTkzMTMxNX0.4exGVSL4bzbwf9QqgjP3IFXfufA_1pl5Jc2nGrW58lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);